"""The eight pipeline stages.

Each function builds the argv for a vendored upstream script from the resolved
config and hands it to runner.run_stage. Stages communicate through a fixed
directory layout under paths.work_dir:

    work_dir/
      tiles/                          step 1  (DeepPATH tiles)
      hdf5/<dataset>_he_complete.h5   step 2  (HPL-format tile store)
      hpl/..._filtered.h5             step 3  (img_z_latent embeddings)
      clusters/                       steps 4-5 (HPC assignment + artifact filter)
      datasets/<dataset>/<model>/     step 6  (SurvCLAM .pt feature store + tile_ids)
      survclam/                       step 7  (per-fold predictions + chips_scores.csv)
      attention/                      step 8  (per-tile attention + overlays)

Every function takes (cfg, opts) where opts carries dry_run / no_env_switch.
"""
from __future__ import annotations

import os
from pathlib import Path

from .config import require
from .runner import run_stage


def _mkdir(opts, path):
    """Create a directory unless we are in dry-run; always return the path."""
    if not getattr(opts, "dry_run", False):
        Path(path).mkdir(parents=True, exist_ok=True)
    return str(path)

# --------------------------------------------------------------------------
# Shared helpers
# --------------------------------------------------------------------------

TILING_ENV_KEY = "tiling"
SURVCLAM_ENV_KEY = "survclam"


def _work(cfg, *parts) -> str:
    base = require(cfg, "paths.work_dir")
    return str(Path(base, *parts))


def _tool(cfg, which) -> str:
    return require(cfg, f"tools.{which}_root")


def _hdf5_path(cfg) -> str:
    ds = cfg.get("dataset_name", "cohort")
    return _work(cfg, "hdf5", f"hdf5_{ds}_he_complete.h5")


def _projected_h5(cfg) -> str:
    """Step 3 output: raw projected embeddings (before artifact removal)."""
    ds = cfg.get("dataset_name", "cohort")
    return _work(cfg, "hpl", f"hdf5_{ds}_he_complete.h5")


def _filtered_h5(cfg) -> str:
    """Step 4 output: artifact tiles removed. remove_indexes_h5.py appends
    '_filtered' to the input h5 stem, so this must match that convention."""
    ds = cfg.get("dataset_name", "cohort")
    return _work(cfg, "hpl", f"hdf5_{ds}_he_complete_filtered.h5")


def _pt_features_root(cfg) -> str:
    return _work(cfg, "datasets")


def _run_sig(cfg) -> str:
    """Rebuild SurvCLAM's run signature (must match training / eval.py).

    make_run_signature_simple(survival, time_col, covariates, bag_level) ->
      survival__{time_col}__{no_covariates|<slug>_covariates}__{bag}_level
    """
    inf = cfg.get("infer", {})
    time_col = inf.get("time_col", "dfs_event_data")
    covs = (inf.get("covariate_cols") or "").strip()
    if covs:
        slug = "_".join(c.strip().lower() for c in covs.split(",") if c.strip())
        cov_part = f"{slug}_covariates"
    else:
        cov_part = "no_covariates"
    bag = inf.get("bag_level", "patient")
    return f"survival__{time_col}__{cov_part}__{bag}_level"


def _results_dir(cfg) -> str:
    """Directory holding s_{fold}_checkpoint.pt for the shipped model."""
    inf = cfg.get("infer", {})
    runs_root = require(cfg, "weights.survclam_runs_root")
    return os.path.join(
        runs_root, inf.get("runs_root_dataset", "colon_united"),
        _run_sig(cfg), "results",
        f"{inf.get('exp_code')}_s{inf.get('seed', 1)}",
    )


def _manifest_csv(cfg) -> str:
    """Minimal per-slide manifest generated by step_assign_hpc.

    Used as the clinical CSV fallback for steps 6-8 when the collaborator has no
    outcome labels: carries slide_id, case_id, and dummy time/event columns so
    the SurvCLAM dataset builds and risk (CHiPS) is still produced.
    """
    return _work(cfg, "clusters", f"{cfg.get('dataset_name','cohort')}_manifest.csv")


def _clinical_or_manifest(cfg) -> str:
    return cfg.get("paths", {}).get("clinical_csv", "") or _manifest_csv(cfg)


def _external_split_csv(cfg) -> str:
    """A CLAM-style split CSV listing every cohort slide in the `test` column.

    Generated by step_assign_hpc; consumed by the attention extractor, which
    requires a --split_csv even for external inference.
    """
    return _work(cfg, "clusters", f"{cfg.get('dataset_name','cohort')}_external_split.csv")


def _env(cfg, key):
    return cfg.get("envs", {}).get(key)


def _activation(cfg, key):
    """Resolve how a stage is entered: (conda_env_name_or_None, [modules]).

    If envs.<key>_module is set it takes precedence (module load, no conda
    activate); otherwise the conda env envs.<key> is used.
    """
    envs = cfg.get("envs", {})
    mod = envs.get(f"{key}_module", "")
    if mod:
        return None, (mod if isinstance(mod, list) else [mod])
    return envs.get(key), []


# --------------------------------------------------------------------------
# Step 1 — tile WSIs at 20x (DeepPATH)
# --------------------------------------------------------------------------

def step_tile(cfg, opts):
    deeppath = _tool(cfg, "deeppath")
    tiler = os.path.join(deeppath, "DeepPATH_code", "00_preprocessing",
                         "0b_tileLoop_deepzoom4.py")
    wsi_dir = require(cfg, "paths.wsi_dir")
    out_dir = _mkdir(opts, _work(cfg, "tiles"))
    t = cfg.get("tile", {})
    mag = cfg.get("magnification", "20x").rstrip("x")
    # DeepPATH expects a glob of slides as the positional argument.
    wsi_glob = os.path.join(wsi_dir, "*")
    argv = [
        "python", tiler,
        "-s", t.get("tile_size", 224),
        "-e", t.get("overlap", 0),
        "-j", t.get("workers", 8),
        "-B", t.get("background_threshold", 50),
        "-M", mag,
        "-o", os.path.join(out_dir, cfg.get("dataset_name", "cohort")),
        wsi_glob,
    ]
    return run_stage(cfg, step="tile", env=_activation(cfg, TILING_ENV_KEY)[0], modules=_activation(cfg, TILING_ENV_KEY)[1], argv=argv,
                     dry_run=opts.dry_run, no_env_switch=opts.no_env_switch)


# --------------------------------------------------------------------------
# Step 2 — convert tiles to HDF5 (DeepPATH)
# --------------------------------------------------------------------------

def step_to_hdf5(cfg, opts):
    deeppath = _tool(cfg, "deeppath")
    conv = os.path.join(deeppath, "DeepPATH_code", "00_preprocessing",
                        "0e_jpgtoHDF.py")
    tiles_dir = _work(cfg, "tiles")
    out_h5 = _hdf5_path(cfg)
    _mkdir(opts, os.path.dirname(out_h5))
    t = cfg.get("tile", {})
    argv = [
        "python", conv,
        "--input_path", tiles_dir,
        "--output", out_h5,
        "--wSize", t.get("tile_size", 224),
        "--label", "he",
        "--subset", "complete",
    ]
    return run_stage(cfg, step="to_hdf5", env=_activation(cfg, TILING_ENV_KEY)[0], modules=_activation(cfg, TILING_ENV_KEY)[1], argv=argv,
                     dry_run=opts.dry_run, no_env_switch=opts.no_env_switch)


# --------------------------------------------------------------------------
# Step 3 — project tiles into the trained HPL encoder (BarlowTwins_3)
# --------------------------------------------------------------------------

def step_project(cfg, opts):
    hpl = _tool(cfg, "hpl")
    proj = os.path.join(hpl, "run_representationspathology_projection_dataset.py")
    ckpt = require(cfg, "weights.hpl_checkpoint")
    model = cfg.get("weights", {}).get("hpl_model_name", "BarlowTwins_3")
    p = cfg.get("project", {})
    _mkdir(opts, _work(cfg, "hpl"))
    argv = [
        "python", proj,
        "--checkpoint", ckpt,
        "--dataset", cfg.get("dataset_name", "cohort"),
        "--model", model,
        "--img_size", p.get("img_size", 224),
        "--z_dim", p.get("z_dim", 128),
        "--batch_size", p.get("batch_size", 64),
        "--main_path", hpl,
        "--dbs_path", _work(cfg, "hdf5"),
    ]
    return run_stage(cfg, step="project", env=_activation(cfg, TILING_ENV_KEY)[0], modules=_activation(cfg, TILING_ENV_KEY)[1], argv=argv,
                     cwd=hpl, dry_run=opts.dry_run, no_env_switch=opts.no_env_switch)


# --------------------------------------------------------------------------
# Step 4 — artifact removal (coarse clustering + tile-level drop)
# --------------------------------------------------------------------------

def step_cluster_filter(cfg, opts):
    """Assign tiles to the coarse artifact clustering (leiden 5.0, 'cohort'),
    then drop tiles in the artifact clusters at the tile level -> filtered h5.

    (a) HPL assignment of the projected tiles to the reference artifact
        clustering; (b) build the remove-index pickle from that assignment and
        run remove_indexes_h5.py (see pancolon/artifact_filter.py).
    """
    hpl = _tool(cfg, "hpl")
    assign = os.path.join(hpl, "run_representationsleiden_assignment.py")
    c = cfg.get("cluster", {})
    # (a) assign to the artifact clustering
    argv = [
        "python", assign,
        "--resolution", c.get("artifact_resolution", 5.0),
        "--meta_field", c.get("artifact_meta_field", "cohort"),
        "--rep_key", c.get("rep_key", "img_z_latent"),
        "--folds_pickle", require(cfg, "weights.hpl_folds_pickle"),
        "--main_path", hpl,
        "--h5_complete_path", require(cfg, "weights.hpl_artifact_reference_h5"),
        "--h5_additional_path", _projected_h5(cfg),
    ]
    run_stage(cfg, step="cluster_filter", env=_activation(cfg, TILING_ENV_KEY)[0], modules=_activation(cfg, TILING_ENV_KEY)[1],
              argv=argv, cwd=hpl,
              dry_run=opts.dry_run, no_env_switch=opts.no_env_switch)
    # (b) build remove-index pickle + remove tiles -> _filtered_h5
    from . import artifact_filter
    return artifact_filter.remove_artifacts(cfg, opts, _projected_h5(cfg))


# --------------------------------------------------------------------------
# Step 5 — HPC assignment on the artifact-filtered tiles
# --------------------------------------------------------------------------

def step_assign_hpc(cfg, opts):
    """Assign the surviving (filtered) tiles to the fine HPC clustering
    (leiden 2.5, 'cohort_cleaned'), then materialize the per-tile HPC table +
    per-slide manifest + external split used by steps 6-8.
    """
    hpl = _tool(cfg, "hpl")
    assign = os.path.join(hpl, "run_representationsleiden_assignment.py")
    c = cfg.get("cluster", {})
    # (a) assign filtered tiles to the HPC clustering
    argv = [
        "python", assign,
        "--resolution", c.get("hpc_resolution", 2.5),
        "--meta_field", c.get("hpc_meta_field", "cohort_cleaned"),
        "--rep_key", c.get("rep_key", "img_z_latent"),
        "--folds_pickle", require(cfg, "weights.hpl_folds_pickle"),
        "--main_path", hpl,
        "--h5_complete_path", require(cfg, "weights.hpl_reference_h5"),
        "--h5_additional_path", _filtered_h5(cfg),
    ]
    run_stage(cfg, step="assign_hpc", env=_activation(cfg, TILING_ENV_KEY)[0], modules=_activation(cfg, TILING_ENV_KEY)[1],
              argv=argv, cwd=hpl,
              dry_run=opts.dry_run, no_env_switch=opts.no_env_switch)
    # (b) standardize the per-tile HPC table + manifest + split
    from . import hpc_assign
    out_csv = _work(cfg, "clusters", f"{cfg.get('dataset_name','cohort')}_hpc_assignment.csv")
    _mkdir(opts, os.path.dirname(out_csv))
    return hpc_assign.build_assignment_table(cfg, out_csv, dry_run=opts.dry_run)


# --------------------------------------------------------------------------
# Step 6 — build the SurvCLAM .pt feature store from HPL embeddings
# --------------------------------------------------------------------------

def step_build_pt(cfg, opts):
    survclam = _tool(cfg, "survclam")
    script = os.path.join(survclam, "save_embeddings_hpl.py")
    b = cfg.get("build_pt", {})
    p = cfg.get("project", {})
    clinical = _clinical_or_manifest(cfg)
    argv = [
        "python", script,
        "--dataset_name", cfg.get("dataset_name", "cohort"),
        "--clinical_csv", clinical,
        "--slide_id_col", cfg.get("paths", {}).get("slide_id_col", "slide_id"),
        "--features_root", _pt_features_root(cfg),
        "--model", b.get("model_key", "HPL_PANCOLON_20x"),
        "--mag", cfg.get("magnification", "20x"),
        "--h5", _filtered_h5(cfg),   # artifact-removed embeddings
        "--meta_field", b.get("meta_field", "slides"),
        "--rep_key", p.get("rep_key", "img_z_latent"),
        "--tiles_key", p.get("tiles_key", "tiles"),
        "--strip_files_suffix",
    ]
    return run_stage(cfg, step="build_pt", env=_activation(cfg, SURVCLAM_ENV_KEY)[0], modules=_activation(cfg, SURVCLAM_ENV_KEY)[1],
                     argv=argv, cwd=survclam,
                     dry_run=opts.dry_run, no_env_switch=opts.no_env_switch)


# --------------------------------------------------------------------------
# Step 7 — apply the trained CHiPS fold checkpoints (external inference)
# --------------------------------------------------------------------------

def step_infer_survival(cfg, opts):
    survclam = _tool(cfg, "survclam")
    script = os.path.join(survclam, "eval.py")
    inf = cfg.get("infer", {})
    b = cfg.get("build_pt", {})
    feature_dir = _work(cfg, "datasets", cfg.get("dataset_name", "cohort"),
                        b.get("model_key", "HPL_PANCOLON_20x"), "pt_files")
    save_dir = _mkdir(opts, _work(cfg, "survclam"))
    clinical = _clinical_or_manifest(cfg)
    # --split all => score every slide against every fold (external inference,
    # no split CSVs needed). Checkpoints are found via runs_root/dataset/run_sig.
    argv = [
        "python", script,
        "--dataset_name", inf.get("runs_root_dataset", "colon_united"),
        "--clinical_csv", clinical,
        "--runs_root", require(cfg, "weights.survclam_runs_root"),
        "--exp_code", inf.get("exp_code"),
        "--seed", inf.get("seed", 1),
        "--task_type", inf.get("task_type", "survival"),
        "--time_col", inf.get("time_col", "dfs_event_data"),
        "--event_col", inf.get("event_col", "dfs_event_ind"),
        "--bag_level", inf.get("bag_level", "patient"),
        "--pt_id_col", inf.get("pt_id_col", "slide_id"),
        "--feature_dir", feature_dir,
        "--embed_dim", b.get("embed_dim", 128),
        "--fold", -1,
        "--split", "all",
        "--k", inf.get("k", 16),
    ]
    if inf.get("covariate_cols"):
        argv += ["--covariate_cols", inf["covariate_cols"],
                 "--cov_fusion", inf.get("cov_fusion", "concat")]
    extra = {"CHIPS_SAVE_DIR": save_dir}
    rc = run_stage(cfg, step="infer_survival", env=_activation(cfg, SURVCLAM_ENV_KEY)[0], modules=_activation(cfg, SURVCLAM_ENV_KEY)[1],
                   argv=argv, cwd=survclam, extra_env=extra,
                   dry_run=opts.dry_run, no_env_switch=opts.no_env_switch)
    if not opts.dry_run:
        from . import chips
        chips.aggregate_folds(cfg, save_dir)
    return rc


# --------------------------------------------------------------------------
# Step 8 — per-tile attention + CHiPS-annotated overlays
# --------------------------------------------------------------------------

def step_attention_map(cfg, opts):
    survclam = _tool(cfg, "survclam")
    script = os.path.join(survclam, "extract_last_layer_and_attention.py")
    inf = cfg.get("infer", {})
    b = cfg.get("build_pt", {})
    a = cfg.get("attention", {})
    results_dir = _results_dir(cfg)
    feature_dir = _work(cfg, "datasets", cfg.get("dataset_name", "cohort"),
                        b.get("model_key", "HPL_PANCOLON_20x"), "pt_files")
    tile_locs_dir = _work(cfg, "datasets", cfg.get("dataset_name", "cohort"),
                         b.get("model_key", "HPL_PANCOLON_20x"), "tile_ids")
    out_dir = _mkdir(opts, _work(cfg, "attention"))
    clinical = _clinical_or_manifest(cfg)
    # One representative fold's checkpoint drives the attention weights; the
    # CHiPS score annotated on each slide comes from step 7's aggregate.
    fold = 0 if inf.get("chips_folds", "all") == "all" else \
        int(str(inf["chips_folds"]).split(",")[0])
    split_csv = _external_split_csv(cfg)
    argv = [
        "python", script,
        "--results_dir", results_dir,
        "--split_csv", split_csv,
        "--dataset_name", cfg.get("dataset_name", "cohort"),
        "--clinical_csv", clinical,
        "--feature_dir", feature_dir,
        "--task_type", inf.get("task_type", "survival"),
        "--time_col", inf.get("time_col", "dfs_event_data"),
        "--event_col", inf.get("event_col", "dfs_event_ind"),
        "--bag_level", inf.get("bag_level", "patient"),
        "--fold", fold,
        "--tile_locs_dir", tile_locs_dir,
        "--out_dir", out_dir,
        "--which_sets", a.get("which_sets", "test"),
        "--skip_missing_slide_pt",
    ]
    return run_stage(cfg, step="attention_map", env=_activation(cfg, SURVCLAM_ENV_KEY)[0], modules=_activation(cfg, SURVCLAM_ENV_KEY)[1],
                     argv=argv, cwd=survclam,
                     dry_run=opts.dry_run, no_env_switch=opts.no_env_switch)


# --------------------------------------------------------------------------
# Ordered registry
# --------------------------------------------------------------------------

STEPS = [
    ("tile", step_tile, "Tile whole-slide images at the target magnification (DeepPATH)"),
    ("to_hdf5", step_to_hdf5, "Convert tiles to an HDF5 tile store (DeepPATH)"),
    ("project", step_project, "Project tiles into the trained HPL encoder -> embeddings"),
    ("cluster_filter", step_cluster_filter, "Artifact removal: coarse clustering + tile drop"),
    ("assign_hpc", step_assign_hpc, "Assign surviving tiles to HPCs (Leiden 2.5)"),
    ("build_pt", step_build_pt, "Build the SurvCLAM .pt feature store"),
    ("infer_survival", step_infer_survival, "Score slides with the CHiPS fold checkpoints"),
    ("attention_map", step_attention_map, "Extract attention + render CHiPS overlays"),
]

STEP_MAP = {name: fn for name, fn, _ in STEPS}
STEP_ORDER = [name for name, _, _ in STEPS]
